SET search_path TO nounous;


-- Schéma

DROP SCHEMA IF EXISTS nounous CASCADE;
CREATE SCHEMA nounous AUTHORIZATION nounous;
GRANT ALL PRIVILEGES ON SCHEMA nounous TO nounous;


-- Tables

CREATE TABLE compte(
   IdCompte INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   Email VARCHAR(25) NOT NULL,
   Motdepasse VARCHAR(250) NOT NULL,
   Pseudo VARCHAR(25) NOT NULL,
   Role VARCHAR(50) NOT NULL,
   PRIMARY KEY(IdCompte)
 
);

CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR','PARENT') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE categorie (
	IdCategorie		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Libelle			VARCHAR(25)		NOT NULL,
	PRIMARY KEY (IdCategorie)
);

CREATE TABLE personne (
	IdPersonne		INT				NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	IdCategorie		INT				NOT NULL,
	Nom				VARCHAR(25)  	NOT NULL,
	Prenom			VARCHAR(25) 	NOT NULL,
	FOREIGN KEY (IdCategorie) REFERENCES categorie (IdCategorie),
	PRIMARY KEY (IdPersonne)
);

CREATE TABLE parent(
   IdParent     INT NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   Nom VARCHAR(250) NOT NULL,
   Prenom VARCHAR(250) NOT NULL,
   Adresse VARCHAR(250),
   IdCompte SMALLINT NOT NULL,
   PRIMARY KEY(IdParent),
   UNIQUE(IdCompte),
   FOREIGN KEY(IdCompte) REFERENCES compte(IdCompte)
);

CREATE TABLE nounou(
   IdNounou   INT NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   Nom VARCHAR(250) NOT NULL,
   Prenom VARCHAR(250) NOT NULL,
   Adresse VARCHAR(250),
   IdCompte SMALLINT NOT NULL,
   Telephone			VARCHAR(25)		NOT NULL,
   PRIMARY KEY(IdNounou),
   UNIQUE(IdCompte),
   FOREIGN KEY(IdCompte) REFERENCES compte(IdCompte)
);

CREATE TABLE telephone (
	IdTelephone		  INT NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	IdPersonne		INT			 	NOT NULL,
	IdParent		INT			 	NOT NULL,
	Libelle			VARCHAR(25)		NOT NULL,
	Numero			VARCHAR(25)		NOT NULL,
	FOREIGN KEY (IdPersonne) REFERENCES personne (IdPersonne),
    FOREIGN KEY(IdParent) REFERENCES parent(IdParent),
    FOREIGN KEY(IdNounou) REFERENCES nounou(IdNounou),
	PRIMARY KEY (IdTelephone)
);

CREATE TABLE contrat(
   IdContrat INT NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   TarifHoraire DECIMAL(15,2) NOT NULL,
   NbreHeuresEntretien TIME NOT NULL,
   TarifRepas DECIMAL(15,2) NOT NULL,
   IdParent INT NOT NULL,
   IdNounou INT NOT NULL,
   DateDeGarde DATE NOT NULL,
   HeureArrivee TIME NOT NULL,
   HeureDepart TIME NOT NULL,
   Repas BOOLEAN NOT NULL,
   PRIMARY KEY(IdContrat),
   FOREIGN KEY(IdParent) REFERENCES parent(IdParent),
   FOREIGN KEY(IdNounou) REFERENCES nounou(IdNounou)
);
CREATE TABLE enfant(
   IdEnfant INT NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
   NomEnfant VARCHAR(250) NOT NULL,
   PrenomEnfant VARCHAR(250) NOT NULL,
   DateNaissance DATE NOT NULL,
   IdParent SMALLINT NOT NULL,
   PRIMARY KEY(IdEnfant),
   FOREIGN KEY(IdParent) REFERENCES parent(IdParent)
);




